version: "3"
services:
  tcc_sonarqube:
    image: sonarqube:latest
    container_name: tcc_sonarqube
    ports:
      - 2000:9000
      - 9092:9092
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://tcc_sonarqube-db:5432/sonar
    volumes:
      - tcc_sonarqube_conf:/opt/sonarqube/conf
      - tcc_sonarqube_data:/opt/sonarqube/data
      - tcc_sonarqube_extensions:/opt/sonarqube/extensions
      - tcc_sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    links:
      - tcc_sonarqube-db
  tcc_sonarqube-db:
    image: postgres:latest
    container_name: tcc_sonarqube-db
    ports:
      - 2001:5432
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - tcc_sonarqube_db:/var/lib/postgresql/data
volumes:
  tcc_sonarqube_conf:
  tcc_sonarqube_data:
  tcc_sonarqube_extensions:
  tcc_sonarqube_bundled-plugins:
  tcc_sonarqube_db:
